---
title: "UpdatedFig3"
author: "Andy"
date: "2022-10-12"
output: pdf_document
---

```{r}
require(emdbook)
require(bbmle)
require(R2WinBUGS)
require(plotrix)
require(plyr)
require(Hmisc)
require(broom)
require(ggplot2)
source("../pantala/ModelingFunctions.R")
frdat <- read.csv("../pantala/TDFR_Pantala-Atro_data.csv")
devdata <- read.csv( "../figs/AeAtro_TDDevData.csv" )
dev_confints.dat <- read.csv( "../figs/ConfInts_AeAtro_TDDev.csv" )
mort_confints.dat <- read.csv( "../figs/ConfInts_AeAtro_TDMort.csv" )

```


```{r}
## Panel A -- Temp. dependent development
Fig3a.plot <- ggplot( data = devdata, aes( x = Temp, y = DevTime ) ) +
  geom_point( size = 2 ) +
  stat_function( fun = arr.time, 
                 args = list( c_dev = 0.41171, b_dev = -34.52544 ) ) +
  geom_ribbon( aes( x = Temp, y = mean, ymin = lcl, ymax = ucl ), data = dev_confints.dat, alpha = 0.3 ) +
  xlab( "Temperature (째C)" ) +
  ylab( "Development Time (days)" ) +
  scale_x_continuous( limits = c( 18, 38 ), 
                      breaks = c( 20, 24, 28, 32, 36 ) ) +
  theme_classic( base_size = 24, base_line_size = 1 ) + 
  theme( panel.border = element_rect( color = "black", fill = NA, size = 0.75 ),
         aspect.ratio = 1 )


ggsave("../figs/Fig3a.png", plot = Fig3a.plot, units = c( "mm" ), dpi = 300, bg = "white" )
```

```{r}
## Panel B -- Temp. dependent mortality
Fig3b.plot <- ggplot( data = devdata, aes( x = Temp, y = 1 - MortalityRate ) ) +
  geom_point( size = 2, colour = "#F8766D") +
  stat_function( fun = logisticfun,
                 args = list( x1 = 37.77558593, y1 = 0.015932967, r_mort = 1.289955323),
                 linetype = "solid",
                 colour = "#F8766D",
                 size = 1 ) +  
  xlab( "Temperature (째C)" ) +
  geom_ribbon( aes( x = Temp, y = 1 - mean, ymin = 1 - lcl, ymax = 1 - ucl ), data = mort_confints.dat, alpha = 0.3, fill = "#F8766D") +
  ylab( "Proportional Survival" ) +
  scale_x_continuous( breaks = c( 20, 24, 28, 32, 36 ) ) +
  scale_y_continuous( expand = c(0, 0), breaks = c(0.80, 0.85, 0.90, 0.95, 1.00) ) +
  coord_cartesian( xlim = c( 19, 37), ylim = c(0.8, 1.01) ) +
  theme_classic( base_size = 24, base_line_size = 1 ) + 
  theme( panel.border = element_rect( color = "black", fill = NA, size = 0.75 ),
         aspect.ratio = 1 )


ggsave("../figs/Fig3b.png", plot = Fig3b.plot, units = c( "mm" ), dpi = 300, bg = "white" )
```

```{r}
## Panel C -- Temp. dependent FR
predparms <- read.csv( "../pantala/Parms_Pan_FR_Wide.csv" )

N0_vec <- seq( 0, 125, by = 1 )
TempK_fac <- c( 293.15, 297.15, 301.15, 305.15, 309.15 )
ddepfr_out.dat <- mat.or.vec( nrow( predparms ) * length( TempK_fac ) * length ( N0_vec ), 4)
colnames( ddepfr_out.dat ) <- c( "Pred", "Temp", "N0", "Killed" )
row <- 0

for(h in 1:nrow( predparms ) ){
  for ( i in 1:length( N0_vec ) ){
    for (j in 1:length( TempK_fac ) ){
      row <- row + 1
      ddepfr_out.dat[ row, "Pred" ] <- predparms[ h, 1 ]
      ddepfr_out.dat[ row,"Temp" ] <- TempK_fac[ j ] - 273.15
      ddepfr_out.dat[ row, "N0" ] <- N0_vec[ i ]
      ddepfr_out.dat[ row, "Killed" ] = rogers.sentis( N0 = N0_vec[ i ], 
                                                       b = exp( predparms[ h, 2 ] ), 
                                                       T0 = predparms[ h, 6 ], 
                                                       Tl = predparms[ h, 7 ], 
                                                       h0 = exp( predparms[ h, 3 ] ), 
                                                       Eh = exp( predparms[ h, 4 ] ), 
                                                       M = predparms[ h, 5 ], 
                                                       bh = 0.75, 
                                                       k = 8.617e-5, 
                                                       TempK = TempK_fac[ j ], 
                                                       t = 1 )
    }
  }
}

ddepfr_out.dat <- as.data.frame( ddepfr_out.dat )
ddepfr_out.dat$Pred <- as.factor(ddepfr_out.dat$Pred)
ddepfr_out.dat$Temp <- as.factor(ddepfr_out.dat$Temp)
ddepfr_out.dat$N0 <- as.numeric(ddepfr_out.dat$N0)
ddepfr_out.dat$Killed <- as.numeric(ddepfr_out.dat$Killed)


frdat$Temp <- as.factor( frdat$Temp )

Fig3c.plot <- ggplot( data.frame( N0 = c( 0, 120 ) ), aes( N0 ) ) +
  geom_point( data = frdat, 
              aes( x = N0, y= Killed, colour = Temp ), size = 2 ) +
  geom_line( data = ddepfr_out.dat, aes( x = N0, y = Killed, colour = Temp ) ) +
  ylab( "Prey Killed" ) +
  xlab( "Prey Density" ) +
  scale_y_continuous( expand = c( 0, 0 ), limits = c( 0, 65 ) ) +
  scale_x_continuous( expand = c( 0, 0 ), limits = c( 0, 125 ), breaks = c(0, 20, 40, 60, 80, 100, 120) ) +
  scale_color_manual( "Temp (째C)", values = c( "blue", "green3", "yellow2", "orange2", "red2" ) ) +
  theme_classic( base_size = 24, base_line_size = 1 ) + 
  theme( panel.border = element_rect( color = "black", fill = NA, size = 0.75 ),
         legend.position = "right",
         aspect.ratio = 1 )

Fig3cLeg.plot <- get_legend(Fig3c.plot)
Fig3c.plot <- Fig3c.plot + theme(legend.position = "none")


ggsave("../figs/Fig3c.png", plot = Fig3c.plot, units = c( "mm" ), dpi = 300, bg = "white" )
ggsave("../figs/Fig3cLeg.png", plot = Fig3cLeg.plot, units = c( "mm" ), dpi = 300, bg = "white" )
```

```{r}
## Panel D -- Model out
modelout.df <- read.csv( "../pantala/Output_PanSpp.csv" )

Fig3d.plot <- ggplot( modelout.df, aes( x = temp, y = num_survive/300 ) ) +
  geom_smooth( colour = "#00BFC4", fill = "#00BFC4", alpha = 0.3 ) +
  scale_x_continuous( expand = c( 0, 0 ), limits = c(18, 38), breaks = c( 20, 24, 28, 32, 36 ) ) +
  scale_y_continuous( expand = c( 0, 0 ) ) +
  coord_cartesian( ylim = c( 0.10, 0.30 ) ) +
  theme_classic( base_size = 24, base_line_size = 1 ) +
  theme( panel.border = element_rect( color = "black", fill = NA, size = 0.75 ),
         legend.position = "bottom",
         aspect.ratio = 1) + 
  xlab( "Temperature (째C)" ) +
  ylab( "Proportional Survival" )


ggsave("../figs/Fig3d.png", plot = Fig3d.plot, units = c( "mm" ), dpi = 300, bg = "white" )
```